### ISSUE TITLE
Get info in example_agent?

### ISSUE THREAD

**Issue by vrodriguezf** [mit-ll/spacegym-kspdg#4]
Hi,

If I understand correctly, the evaluation is done with an `AgentRunner` class, like this:
```python
if __name__ == "__main__":
    naive_agent = NaivePursuitAgent()    
    runner = AgentEnvRunner(
        agent=naive_agent, 
        env_cls=PE1_E1_I3_Env, 
        env_kwargs=None,
        runner_timeout=100,     # agent runner that will timeout after 100 seconds
        debug=True)
    runner.run()
```

And the Agent class defines the get_action method like this:
```python
class KSPDGBaseAgent(ABC):
    @abstractmethod
    def get_action(self, observation):
        raise NotImplementedError("Must be implemented by child class")
```

Therefore, the agent can only access the observation space, but not the updated info of the environment nor the reward. However, in the hello_world example the agent is coded like this:
```python
while not is_done:
    obs, rew, is_done, info = env.step(act)
```

So the call to step can return everything needed (obs, reward, finished, and info). 

How can you get everything that you get in the format of the hello_world, but encapsuled under the interface of KSPDGBaseAgent.get_action?

Thank you!
Víctor

**Comment by rallen10** [comment]
@vrodriguezf the intention here is that---from the agent's perspective---the only information they have available to make control decisions during runtime is the observation. Reward and "info" is generally meant for analysis of agent performance, and perhaps training of the agent if reinforcement learning is to be used; it's generally not meant for use by the agent to make decisions from one time-step to another.

If there is further information that would be useful for control decisions, let me know and I can look to add it to the observation space (also feel free to make pull requests with chages). You generally don't want to dump every conceivable piece of information into the observation space since it adds a lot of "noise" to a learning process (again, mostly relevant if model-free RL is being used).

Having more direct access to the reward signal is a bit different. If you are using a temporal differencing RL method, you do need access to reward values at each time step. However, as I mentioned in the kickoff meeting, this library is intentionally designed for evaluation of agents; not for training agents. Therefore making the functions fully compatible with RL pipelines is out of scope here. Participants would need to develop their own training environments and then transfer their trained agents to run in KSPDG.

**Comment by vrodriguezf** [comment]
Ok, thank you for the detailed explanation Ross!
